/*
 * This file is generated by jOOQ.
 */
package kz.mukha.wallet.data.jooq.postgres.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import kz.mukha.wallet.data.jooq.postgres.tables.Wallets;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WalletsRecord extends UpdatableRecordImpl<WalletsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>wallet.wallets.wallet_id</code>.
     */
    public void setWalletId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>wallet.wallets.wallet_id</code>.
     */
    public UUID getWalletId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>wallet.wallets.owner_id</code>.
     */
    public void setOwnerId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>wallet.wallets.owner_id</code>.
     */
    public UUID getOwnerId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>wallet.wallets.wallet_name</code>.
     */
    public void setWalletName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wallet.wallets.wallet_name</code>.
     */
    public String getWalletName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wallet.wallets.currency</code>.
     */
    public void setCurrency(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wallet.wallets.currency</code>.
     */
    public String getCurrency() {
        return (String) get(3);
    }

    /**
     * Setter for <code>wallet.wallets.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>wallet.wallets.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>wallet.wallets.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>wallet.wallets.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>wallet.wallets.save_items</code>.
     */
    public void setSaveItems(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>wallet.wallets.save_items</code>.
     */
    public Boolean getSaveItems() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WalletsRecord
     */
    public WalletsRecord() {
        super(Wallets.WALLETS);
    }

    /**
     * Create a detached, initialised WalletsRecord
     */
    public WalletsRecord(UUID walletId, UUID ownerId, String walletName, String currency, LocalDateTime createdAt, LocalDateTime updatedAt, Boolean saveItems) {
        super(Wallets.WALLETS);

        setWalletId(walletId);
        setOwnerId(ownerId);
        setWalletName(walletName);
        setCurrency(currency);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setSaveItems(saveItems);
        resetChangedOnNotNull();
    }
}
