/*
 * This file is generated by jOOQ.
 */
package kz.mukha.wallet.data.jooq.postgres.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import kz.mukha.wallet.data.jooq.postgres.Keys;
import kz.mukha.wallet.data.jooq.postgres.Wallet;
import kz.mukha.wallet.data.jooq.postgres.tables.Users.UsersPath;
import kz.mukha.wallet.data.jooq.postgres.tables.Wallets.WalletsPath;
import kz.mukha.wallet.data.jooq.postgres.tables.records.UserWalletPermissionsRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserWalletPermissions extends TableImpl<UserWalletPermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>wallet.user_wallet_permissions</code>
     */
    public static final UserWalletPermissions USER_WALLET_PERMISSIONS = new UserWalletPermissions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserWalletPermissionsRecord> getRecordType() {
        return UserWalletPermissionsRecord.class;
    }

    /**
     * The column <code>wallet.user_wallet_permissions.permission_id</code>.
     */
    public final TableField<UserWalletPermissionsRecord, UUID> PERMISSION_ID = createField(DSL.name("permission_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>wallet.user_wallet_permissions.user_id</code>.
     */
    public final TableField<UserWalletPermissionsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>wallet.user_wallet_permissions.wallet_id</code>.
     */
    public final TableField<UserWalletPermissionsRecord, UUID> WALLET_ID = createField(DSL.name("wallet_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>wallet.user_wallet_permissions.permission_type</code>.
     */
    public final TableField<UserWalletPermissionsRecord, String> PERMISSION_TYPE = createField(DSL.name("permission_type"), SQLDataType.VARCHAR(63).nullable(false).defaultValue(DSL.field(DSL.raw("'WRITE'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>wallet.user_wallet_permissions.created_at</code>.
     */
    public final TableField<UserWalletPermissionsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>wallet.user_wallet_permissions.updated_at</code>.
     */
    public final TableField<UserWalletPermissionsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private UserWalletPermissions(Name alias, Table<UserWalletPermissionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserWalletPermissions(Name alias, Table<UserWalletPermissionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>wallet.user_wallet_permissions</code> table
     * reference
     */
    public UserWalletPermissions(String alias) {
        this(DSL.name(alias), USER_WALLET_PERMISSIONS);
    }

    /**
     * Create an aliased <code>wallet.user_wallet_permissions</code> table
     * reference
     */
    public UserWalletPermissions(Name alias) {
        this(alias, USER_WALLET_PERMISSIONS);
    }

    /**
     * Create a <code>wallet.user_wallet_permissions</code> table reference
     */
    public UserWalletPermissions() {
        this(DSL.name("user_wallet_permissions"), null);
    }

    public <O extends Record> UserWalletPermissions(Table<O> path, ForeignKey<O, UserWalletPermissionsRecord> childPath, InverseForeignKey<O, UserWalletPermissionsRecord> parentPath) {
        super(path, childPath, parentPath, USER_WALLET_PERMISSIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserWalletPermissionsPath extends UserWalletPermissions implements Path<UserWalletPermissionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserWalletPermissionsPath(Table<O> path, ForeignKey<O, UserWalletPermissionsRecord> childPath, InverseForeignKey<O, UserWalletPermissionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserWalletPermissionsPath(Name alias, Table<UserWalletPermissionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserWalletPermissionsPath as(String alias) {
            return new UserWalletPermissionsPath(DSL.name(alias), this);
        }

        @Override
        public UserWalletPermissionsPath as(Name alias) {
            return new UserWalletPermissionsPath(alias, this);
        }

        @Override
        public UserWalletPermissionsPath as(Table<?> alias) {
            return new UserWalletPermissionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Wallet.WALLET;
    }

    @Override
    public UniqueKey<UserWalletPermissionsRecord> getPrimaryKey() {
        return Keys.USER_WALLET_PERMISSIONS_PKEY;
    }

    @Override
    public List<ForeignKey<UserWalletPermissionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_WALLET_PERMISSIONS__USER_WALLET_PERMISSIONS_USER_ID_FKEY, Keys.USER_WALLET_PERMISSIONS__USER_WALLET_PERMISSIONS_WALLET_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>wallet.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.USER_WALLET_PERMISSIONS__USER_WALLET_PERMISSIONS_USER_ID_FKEY, null);

        return _users;
    }

    private transient WalletsPath _wallets;

    /**
     * Get the implicit join path to the <code>wallet.wallets</code> table.
     */
    public WalletsPath wallets() {
        if (_wallets == null)
            _wallets = new WalletsPath(this, Keys.USER_WALLET_PERMISSIONS__USER_WALLET_PERMISSIONS_WALLET_ID_FKEY, null);

        return _wallets;
    }

    @Override
    public UserWalletPermissions as(String alias) {
        return new UserWalletPermissions(DSL.name(alias), this);
    }

    @Override
    public UserWalletPermissions as(Name alias) {
        return new UserWalletPermissions(alias, this);
    }

    @Override
    public UserWalletPermissions as(Table<?> alias) {
        return new UserWalletPermissions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserWalletPermissions rename(String name) {
        return new UserWalletPermissions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserWalletPermissions rename(Name name) {
        return new UserWalletPermissions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserWalletPermissions rename(Table<?> name) {
        return new UserWalletPermissions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserWalletPermissions where(Condition condition) {
        return new UserWalletPermissions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserWalletPermissions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserWalletPermissions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserWalletPermissions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserWalletPermissions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserWalletPermissions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserWalletPermissions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserWalletPermissions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserWalletPermissions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserWalletPermissions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
